language: emacs-lisp

sudo: required

services:
  - docker

before_install:
  - docker pull silex/emacs:26.1-dev

script:
  - ls -l
  - docker run  silex/emacs:26.1-dev /bin/bash -c "emacs --version"
  - docker run  silex/emacs:26.1-dev /bin/bash -c "cask --version"
#  - docker run  silex/emacs:26.1-dev /bin/bash -c "make test"
#  - make test
