language: emacs-lisp

sudo: required

services:
  - docker

before_install:
  - docker pull silex/emacs:27-ci-cask

script:
  - ls -l
  - docker run silex/emacs:27-ci-cask /bin/bash -c "emacs --version"
  - docker run silex/emacs:27-ci-cask /bin/bash -c "cask --version"
  - docker run --mount type=bind,source="$(pwd)",target=/build silex/emacs:27-ci-cask /bin/bash -c "cd build; make test"

